config/routes.rb
Rails.application.routes.draw do
  resources :musics
  devise_for :users
  root to: 'musics#index'
  get "/search", to: "musics#search"
  get "/artist", to: "musics#artist"
  resources :comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :music
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
  # has_attached_file :video, styles: {large: "600x600>",medium: "300x300>", thumb: "100x100>"}
  # validates_attachment_content_type :video, content_type: /\Aimage\/.*\z/
  mount_uploader :video, VideoUploader
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :musics
  has_many :comments
  has_one_attached :img
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @music = Music.find(params[:music_id])
    @comment = @music.comments.create(params[:comment].permit(:name, :comment))
  end

  def destroy
    @music = Music.find(params[:music_id])
    @comment = @music.comments.find(params[:id])
    @comment.destroy
    redirect_to music_path(@music)
  end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
    @user= User.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    @music = Music.find(params[:id])
    # find the user of the creator of that music
    @user= @music.user
    @feedmusics= Music.all

  end

  # GET /musics/new
  def new
    @music = Music.new
  end
  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)
    # prybug
    respond_to do |format|
      # prybug
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        # prybug
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def search
    if params[:search].present?
      sql_query = "name ILIKE :query"
      @musics = Music.where(sql_query, query: "%#{params[:search]}%")
    end
  end

  def artist
    @user= User.find(1)#params[:id])
    @musics = Music.all
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:names, :desc)#, :video)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="shortcut icon" type="image/x-icon" href="assets/dbrop.ico">
    <title>Dbrop</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>

    <%= render 'shared/navbar'%>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/musics/_form.html.erb
<%= simple_form_for [@user,@music], html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :names, required: true, autofocus: true %>
    <%= f.input :desc, required: true, autofocus: true %>
    <%=f.file_field :video, required: true, autofocus: true%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/musics/artist.html.erb
<div class="top1">
  <div class="top1-left">
<!-- artist picture goes here -->
    <img src="<%=@user.img%>" width="400"height="400">
  </div>
  <div class="top1-right">
    <!-- desc of that artist and donate and subscription here with along with information about the artist such as views, likes, links to social media such as facebook and twitter-->
    <h3> <%=@user.name %></h3>
    <h3> Description of the artist</h3>
    <p> <%=@user.desc %></p>
    <button>Donate to the Artist</button>
    <button> Subscribe</button>
  </div>
</div>
<div class= "bottom1">
<div class="col-5 left">
  <div class="row">
    <div class="width">
  <!-- suggest or recommended videos that are related to the video that is being viewed -->
  <h3> Recommended MV</h3>
  <%@musics.each do |music| %>
  <video loop controls onmouseover="this.play()"  loop id="Video">
        <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567576480&ei=P_1uXabVOdCF8gOtlJxA&ip=95.211.60.93&id=o-AFBzALDKA7zH6Eq7xGYf_HQSiFDiWnH4m0pUcWQosQDX&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&beids=23806815&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRgIhAI1jS8TXaxaVTmEYX2LuUAJkwBxGc7LrhEH4vSr368viAiEAmW3ldNCdCUbMeo-7p5UXl1Fd3z1VIt-TpqTwk-v5sGw=&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&fexp=23806815&req_id=1f0d236cd3f3a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567554762&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPp1srsAWh3KFkEMu3T_NwaxO9LlbD6gyDJ3E-U1v0OrAiBiuTqFafNNcTeHo1kNf_GzOw5-fGNCckgMlMBwsYI6UQ==">
      </video>
      <!-- a show page for the song -->
      <%=link_to music_path(music), class: "ref" do %>
        <h3><%=music.name %></h3>
      <% end %>
      <p><%=music.desc %> </p>
      <!-- leads to a profile page where you can donate and subscribe to the artist/user of that account -->
      <%= link_to  "/artist", class: "ref" do%>
        <p><%=music.user.name %></p>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
</div>
<%= render 'shared/footer' %>

app/views/musics/edit.html.erb
<h1>Editing Music</h1>

<%= render 'form', music: @music %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<div class="top">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="false">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h3 id="feature"> Featured Top Music Pick</h3>
        <video controls loop onmouseover="this.play()" onmouseout="this.pause()" loop id="myVideo">
          <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567451054&ei=ThNtXZ2gB4SM1wLRt62AAw&ip=95.211.102.251&id=o-ACv06WryunyqyoXPooMR3E1Ae04EfVKC6fYzgYsHzLXb&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAN-021zgOUrhJIMzlmjAk-HGCVIrCwX-jstqThvXcgyqAiAHN7zVkGXYvzRKOqPwKIeuN5K9k5nlDPNjonXQitvXng==&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&req_id=57f36eef9378a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567429315&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPiRtliH7gH7-AJcIgUgjsmoX_GbT8wk_MWQg1CYfv3-AiBjgosSQp1tl1KWvgZuPfIDzqkuDf19UcfcbPbcOUIUvQ==">
        </video>
       </div>
      <div class="carousel-item">
        <h3 id="feature">Featured Up and Coming Music Pick</h3>
        <video controls loop onmouseover="this.play()" onmouseout="this.pause()" loop id="myVideo">
          <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567451054&ei=ThNtXZ2gB4SM1wLRt62AAw&ip=95.211.102.251&id=o-ACv06WryunyqyoXPooMR3E1Ae04EfVKC6fYzgYsHzLXb&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAN-021zgOUrhJIMzlmjAk-HGCVIrCwX-jstqThvXcgyqAiAHN7zVkGXYvzRKOqPwKIeuN5K9k5nlDPNjonXQitvXng==&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&req_id=57f36eef9378a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567429315&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPiRtliH7gH7-AJcIgUgjsmoX_GbT8wk_MWQg1CYfv3-AiBjgosSQp1tl1KWvgZuPfIDzqkuDf19UcfcbPbcOUIUvQ==">
        </video>
      </div>
      <div class="carousel-item">
        <h3 id="feature">Featured New Music Pick</h3>
        <video controls loop onmouseover="this.play()" onmouseout="this.pause()" loop id="myVideo">
          <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567451054&ei=ThNtXZ2gB4SM1wLRt62AAw&ip=95.211.102.251&id=o-ACv06WryunyqyoXPooMR3E1Ae04EfVKC6fYzgYsHzLXb&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAN-021zgOUrhJIMzlmjAk-HGCVIrCwX-jstqThvXcgyqAiAHN7zVkGXYvzRKOqPwKIeuN5K9k5nlDPNjonXQitvXng==&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&req_id=57f36eef9378a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567429315&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPiRtliH7gH7-AJcIgUgjsmoX_GbT8wk_MWQg1CYfv3-AiBjgosSQp1tl1KWvgZuPfIDzqkuDf19UcfcbPbcOUIUvQ==">
        </video>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="middle">
          <a href="#"><p>Open genre</p></a>
          <a href="#"><p>Blue & Jazz</p></a>
          <a href="#"><p>Classical</p></a>
          <a href="#"><p>Country</p></a>
          <a href="#"><p>Dubstep</p></a>
          <a href="#"><p>EDM</p></a>
          <a href="#"><p>Techno</p></a>
          <a href="#"><p>House</p></a>
          <a href="#"><p>Rock</p></a>

</div>




<div class="bottom">

      <h3>Share your music today!</h3>
      <p>Listen, discover and connect with up and coming music</p>
      <%=link_to "Sign Up - It's Free!", new_user_registration_path, class: "button" %>
    </div>
</div>
</div>

app/views/musics/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>New Music</h1>
      <%= render 'form', music: @music %>
      </br>
      <%= link_to 'Back to Home', musics_path, class: "back-btn"%>
    </div>
  </div>
</div>

app/views/musics/search.html.erb
<div class="top">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="false">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h3 id="feature"> Featured Top Music Pick</h3>
        <video controls loop onmouseover="this.play()" onmouseout="this.pause()" loop id="myVideo">
          <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567451054&ei=ThNtXZ2gB4SM1wLRt62AAw&ip=95.211.102.251&id=o-ACv06WryunyqyoXPooMR3E1Ae04EfVKC6fYzgYsHzLXb&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAN-021zgOUrhJIMzlmjAk-HGCVIrCwX-jstqThvXcgyqAiAHN7zVkGXYvzRKOqPwKIeuN5K9k5nlDPNjonXQitvXng==&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&req_id=57f36eef9378a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567429315&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPiRtliH7gH7-AJcIgUgjsmoX_GbT8wk_MWQg1CYfv3-AiBjgosSQp1tl1KWvgZuPfIDzqkuDf19UcfcbPbcOUIUvQ==">
        </video>
       </div>
      <div class="carousel-item">
        <h3 id="feature">Featured Up and Coming Music Pick</h3>
        <video controls loop onmouseover="this.play()" onmouseout="this.pause()" loop id="myVideo">
          <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567451054&ei=ThNtXZ2gB4SM1wLRt62AAw&ip=95.211.102.251&id=o-ACv06WryunyqyoXPooMR3E1Ae04EfVKC6fYzgYsHzLXb&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAN-021zgOUrhJIMzlmjAk-HGCVIrCwX-jstqThvXcgyqAiAHN7zVkGXYvzRKOqPwKIeuN5K9k5nlDPNjonXQitvXng==&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&req_id=57f36eef9378a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567429315&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPiRtliH7gH7-AJcIgUgjsmoX_GbT8wk_MWQg1CYfv3-AiBjgosSQp1tl1KWvgZuPfIDzqkuDf19UcfcbPbcOUIUvQ==">
        </video>
      </div>
      <div class="carousel-item">
        <h3 id="feature">Featured New Music Pick</h3>
        <video controls loop onmouseover="this.play()" onmouseout="this.pause()" loop id="myVideo">
          <source src="https://r3---sn-uxa0n-tm3e.googlevideo.com/videoplayback?expire=1567451054&ei=ThNtXZ2gB4SM1wLRt62AAw&ip=95.211.102.251&id=o-ACv06WryunyqyoXPooMR3E1Ae04EfVKC6fYzgYsHzLXb&itag=18&source=youtube&requiressl=yes&mime=video%2Fmp4&gir=yes&clen=18070731&ratebypass=yes&dur=243.855&lmt=1538099776967502&fvip=2&c=WEB&txp=5531332&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAN-021zgOUrhJIMzlmjAk-HGCVIrCwX-jstqThvXcgyqAiAHN7zVkGXYvzRKOqPwKIeuN5K9k5nlDPNjonXQitvXng==&title=Sean+Paul+%26amp%3B+Major+Lazer+-+Tip+Pon+It&redirect_counter=1&rm=sn-5hneed7l&req_id=57f36eef9378a3ee&cms_redirect=yes&ipbypass=yes&mip=207.134.138.186&mm=31&mn=sn-uxa0n-tm3e&ms=au&mt=1567429315&mv=m&mvi=2&pl=21&lsparams=ipbypass,mip,mm,mn,ms,mv,mvi,pl&lsig=AHylml4wRQIhAPiRtliH7gH7-AJcIgUgjsmoX_GbT8wk_MWQg1CYfv3-AiBjgosSQp1tl1KWvgZuPfIDzqkuDf19UcfcbPbcOUIUvQ==">
        </video>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div class="col-5 left">
  <div class="row">
    <div class="width">
      <h2 id="centered">Search Results</h2>
      <br>
      <div class="container">
        <div class="row">
          <% if   @musics.present? %>
          <% @musics.each do |music| %>
            <div class="col-12 col-md-12 col-lg-4">
                  <div class="card">
                   ><img src='#'>
                    <div class="card-info">
                      <p><%= music.name %></p>
                      <p><%= music.desc %></p>
                      <h3>$<%= music.views %></h3>
                    </div>
                  </div>
                </div>
              <% end %>
              <% else %>
              <p> No Search Results </p>
              <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="upper-top">
    <ul>
      <li>Follow Us</li>
      <li><a href="#"><i class="fab fa-instagram"></i></a></li>
      <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
      <li><a href="#"><i class="fab fa-twitter-square"></i></a></li>
      <div class="push">
      <li><a href="#">Company</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">News</a></li>
      <li><a href="#">Career</a></li>
      <li><a href="#">Contact Us</a></li>
    </div>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm sticky-top">
  <%= link_to musics_path, class: "navbar-brand item" do %>
    <%= image_tag "logo.png", class: "img" %>
  <% end %>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- if the user is signed in, this is shown on nav bar-->
      <% if user_signed_in? %>

        <li class="item">
          <%= link_to new_music_path do%>
            <button type="button" class="button upload">Upload</button>
          <% end %>
        </li>

        <li class="item">
          <%= link_to destroy_user_session_path, method: :delete do%>
            <button type="button" class="button">Sign Out</button>
          <% end %>
        </li>


        <div action="/search" class="search-box">
          <input type="text" name="" class="search-txt" placeholder="Type to search"/>
          <a class="search-btn" href="/search">
            <i class="fas fa-search"></i>
          </a>
        </div>


      <% else %>

        <li class="item">
          <%= link_to new_user_registration_path do%>
            <button type="button" class="button">Sign Up</button>
          <% end %>
        </li>

        <li class="item">
          <%= link_to new_user_session_path do%>
            <button type="button" class="button">Log In</button>
          <% end %>
        </li>
        </div>

        <div action="/search" class="search-box">
          <input type="text" name="" class="search-txt" placeholder="Type to search"/>
          <a class="search-btn" href="/search">
            <i class="fas fa-search"></i>
          </a>
        </div>
      <% end %>

    </ul>
  </div>
</div>